services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: auth
    ports:
      - 3307:3306
    networks:
      - localnetwork
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:ro,z
  web:
    build: .
    depends_on:
      - db
    environment:
      DB_SERVER: db
      DB_USER: root
      DB_PASSWORD: 12345678
      DB_NAME: auth
    ports:
      - "8001:80"
    networks:
      - localnetwork

networks:
  localnetwork:

